clc;clear
imagepath='F:\Yilong DATA\Results Image\'
addpath(genpath(imagepath)); % image path
addpath(genpath('F:\code\DLLR\stefslon-exportToPPTX')); % exportToPPTX tool path
fileFolder=fullfile(imagepath);
dirOutput=dir(fullfile(fileFolder,'*mat'));
fileNames={dirOutput.name}';
% save([imagepath 'fileNames.mat'],'fileNames')
% load fileNames;
%   Example 1: usage of exportToPPTX with blank presentation
%% Start new presentation
isOpen  = exportToPPTX();
if ~isempty(isOpen),
    % If PowerPoint already started, then close first and then open a new one
    exportToPPTX('close');
end

exportToPPTX('new','Dimensions',[12 6], ...
    'Title','Example Presentation', ...
    'Author','MatLab', ...
    'Subject','Automatically generated PPTX file', ...
    'Comments','This file has been automatically generated by exportToPPTX');

% Additionally background color for all slides can be set as follows:
% exportToPPTX('new','BackgroundColor',[0.5 0.5 0.5]);
%% Add some slides
for i=1:1:size(fileNames,1)
    imagename_i = fileNames(i);
    I_path=char(strcat(imagepath,imagename_i));
    load(I_path);
    figH = figure('Renderer','zbuffer');  imshow(I); 
    slideNum = exportToPPTX('addslide');
    
    fprintf('Added slide %d\n',slideNum);
    exportToPPTX('addpicture',figH);
    str = char(imagename_i);
%     rank_n=regexpi(str,'(?<=rank_).*?(?=.mat)','match');
%     rank_T=['rank truncation is ' char(rank_n) '     '];
    rank_T = str;
    exportToPPTX('addtext',[rank_T '  Left: Reconstruction error x10, Right: SAKE+ESPIRiT reconstruction']);
    exportToPPTX('addnote',sprintf('Notes data: slide number %d',slideNum));  
    
end


%% Check current presentation
fileStats   = exportToPPTX('query');
if ~isempty(fileStats),
    fprintf('Presentation size: %f x %f\n',fileStats.dimensions);
    fprintf('Number of slides: %d\n',fileStats.numSlides);
end


%% Save presentation and close presentation -- overwrite file if it already exists
% Filename automatically checked for proper extension
newFile = exportToPPTX('saveandclose','example');
